site:
  name: Hermandad de San Isidro Labrador
  site: 'https://hermandadsanisidrolabrador.es'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Hermandad de San Isidro Labrador
    template: '%s — Hermandad de San Isidro Labrador'
  description: 'Web de la hermandad de San Isidro Labrador de Alcázar de San Juan'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Hermandad de San Isidro labrador
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    cardType: summary_large_image

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    archivedCategories:
      - articulos
      - entrevistas
      - poemas

    post:
      isEnabled: true
      permalink: '/actualidad/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'actualidad' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categoria' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

  generic: # Generic pages
    isEnabled: true

    page:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

  cults: # Cult pages
    isEnabled: true

    cult:
      isEnabled: true
      permalink: '/%id%/cultos' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

  forms: # Forms pages
    isEnabled: true

    form:
      isEnabled: true
      permalink: '/inscripciones/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

  gallery:
    isEnabled: true
    postsPerPage: 6

    gallery:
      isEnabled: true
      permalink: '/galeria/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    all:
      isEnabled: true
      pathname: 'galeria'
      robots:
        index: true

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
  # rgb(25.5 68.2 34.5)
  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(16 16 16)
        heading: rgb(0 0 0)
        muted: rgb(40 40 40)
        bgPage: rgb(255 255 255)
        primary: rgb(0 124 220)
        secondary: rgb(38,122,56)
        accent: rgb(109 40 217)
        info: rgb(119 182 234)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
    dark:
      fonts: {}
      colors:
        default: rgb(247, 248, 248)
        heading: rgb(247, 248, 248)
        muted: rgb(200, 188, 208)
        bgPage: rgb(3 6 32)
        primary: rgb(29 78 216)
        secondary: rgb(38,122,56)
        accent: rgb(135 77 2267)
        info: rgb(58 191 248)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)

rss:
  instagram: hdadsanisidroalcazar
  facebook: hermandadsanisidro
  whatsapp: "channel/0029VaEjr5LInlqKsafYtN0Q"
