name: Argos CI Screenshots

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.id }}
  cancel-in-progress: true

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpx playwright install --with-deps chromium firefox webkit

      - name: Build the website
        run: pnpm build

      - name: Take screenshots with Playwright
        run: pnpm screenshot

      - name: Upload screenshots to Argos
        run: pnpm exec argos upload ./screenshots
